# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'manualWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_manualWindow(object):
    def setupUi(self, manualWindow):
        manualWindow.setObjectName("manualWindow")
        manualWindow.resize(947, 733)
        self.centralwidget = QtWidgets.QWidget(manualWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnSave = QtWidgets.QPushButton(self.centralwidget)
        self.btnSave.setGeometry(QtCore.QRect(280, 610, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(13)
        self.btnSave.setFont(font)
        self.btnSave.setObjectName("btnSave")
        self.btnEnd = QtWidgets.QPushButton(self.centralwidget)
        self.btnEnd.setGeometry(QtCore.QRect(570, 610, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(13)
        self.btnEnd.setFont(font)
        self.btnEnd.setObjectName("btnEnd")
        self.btnStart = QtWidgets.QPushButton(self.centralwidget)
        self.btnStart.setGeometry(QtCore.QRect(40, 610, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(13)
        self.btnStart.setFont(font)
        self.btnStart.setObjectName("btnStart")
        self.displayContent = QtWidgets.QGraphicsView(self.centralwidget)
        self.displayContent.setGeometry(QtCore.QRect(40, 160, 481, 401))
        self.displayContent.setObjectName("displayContent")
        self.lblDetails = QtWidgets.QLabel(self.centralwidget)
        self.lblDetails.setGeometry(QtCore.QRect(550, 280, 261, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.lblDetails.setFont(font)
        self.lblDetails.setObjectName("lblDetails")
        self.lblDirection1 = QtWidgets.QLabel(self.centralwidget)
        self.lblDirection1.setGeometry(QtCore.QRect(570, 330, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(13)
        font.setKerning(True)
        self.lblDirection1.setFont(font)
        self.lblDirection1.setObjectName("lblDirection1")
        self.lblDirection2 = QtWidgets.QLabel(self.centralwidget)
        self.lblDirection2.setGeometry(QtCore.QRect(570, 380, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(13)
        font.setKerning(True)
        self.lblDirection2.setFont(font)
        self.lblDirection2.setObjectName("lblDirection2")
        self.lblDirection3 = QtWidgets.QLabel(self.centralwidget)
        self.lblDirection3.setGeometry(QtCore.QRect(570, 430, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(13)
        font.setKerning(True)
        self.lblDirection3.setFont(font)
        self.lblDirection3.setObjectName("lblDirection3")
        self.lblDirection4 = QtWidgets.QLabel(self.centralwidget)
        self.lblDirection4.setGeometry(QtCore.QRect(570, 480, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(13)
        font.setKerning(True)
        self.lblDirection4.setFont(font)
        self.lblDirection4.setObjectName("lblDirection4")
        self.lblPositionTopic = QtWidgets.QLabel(self.centralwidget)
        self.lblPositionTopic.setGeometry(QtCore.QRect(550, 110, 261, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.lblPositionTopic.setFont(font)
        self.lblPositionTopic.setObjectName("lblPositionTopic")
        self.lblPosition = QtWidgets.QLabel(self.centralwidget)
        self.lblPosition.setGeometry(QtCore.QRect(570, 150, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(13)
        font.setKerning(True)
        self.lblPosition.setFont(font)
        self.lblPosition.setObjectName("lblPosition")
        self.lblSelect = QtWidgets.QLabel(self.centralwidget)
        self.lblSelect.setGeometry(QtCore.QRect(40, 50, 261, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.lblSelect.setFont(font)
        self.lblSelect.setObjectName("lblSelect")
        self.btnSelect = QtWidgets.QPushButton(self.centralwidget)
        self.btnSelect.setGeometry(QtCore.QRect(250, 60, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(13)
        self.btnSelect.setFont(font)
        self.btnSelect.setObjectName("btnSelect")
        self.lblFileName = QtWidgets.QLabel(self.centralwidget)
        self.lblFileName.setGeometry(QtCore.QRect(390, 60, 411, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lblFileName.setFont(font)
        self.lblFileName.setObjectName("lblFileName")
        manualWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(manualWindow)
        self.statusbar.setObjectName("statusbar")
        manualWindow.setStatusBar(self.statusbar)

        self.retranslateUi(manualWindow)
        QtCore.QMetaObject.connectSlotsByName(manualWindow)

    def retranslateUi(self, manualWindow):
        _translate = QtCore.QCoreApplication.translate
        manualWindow.setWindowTitle(_translate("manualWindow", "Manual Intubation Process"))
        self.btnSave.setText(_translate("manualWindow", "Save Snapshot"))
        self.btnEnd.setText(_translate("manualWindow", "End Process"))
        self.btnStart.setText(_translate("manualWindow", "Start Process"))
        self.lblDetails.setText(_translate("manualWindow", "Operation Details : "))
        self.lblDirection1.setText(_translate("manualWindow", "Direction 1"))
        self.lblDirection2.setText(_translate("manualWindow", "Direction 2"))
        self.lblDirection3.setText(_translate("manualWindow", "Direction 3"))
        self.lblDirection4.setText(_translate("manualWindow", "Direction 4"))
        self.lblPositionTopic.setText(_translate("manualWindow", "Current Tube Position : "))
        self.lblPosition.setText(_translate("manualWindow", "Position"))
        self.lblSelect.setText(_translate("manualWindow", "Select an Video File : "))
        self.btnSelect.setText(_translate("manualWindow", "Select"))
        self.lblFileName.setText(_translate("manualWindow", "No file is selected"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    manualWindow = QtWidgets.QMainWindow()
    ui = Ui_manualWindow()
    ui.setupUi(manualWindow)
    manualWindow.show()
    sys.exit(app.exec_())

